"""Golden-cell tests: the four cells that exercise every binding slot.

Proves: (1) every live cell compiles with zero unbound slots; (2) modes
produce different bindings for the same phase; (3) the invariant core is
byte-identical across modes of the same phase (regimes vary process wording
only through slots); (4) generated bundles carry the GENERATED header.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
COMPOSE = REPO / "compose" / "enter_phase.py"
CELLS = [("research", "paired"), ("research", "auto"),
         ("design", "paired"), ("design", "auto"),
         ("implementation", "auto"), ("validation", "paired"),
         ("debug", "auto")]


def compile_cell(tmp, phase, mode):
    r = subprocess.run([sys.executable, str(COMPOSE), "--project-dir",
                        str(tmp / f"{phase}-{mode}"), "--phase", phase,
                        "--mode", mode], capture_output=True, text=True)
    assert r.returncode == 0, f"{phase}x{mode} refused: {r.stdout}{r.stderr}"
    out = tmp / f"{phase}-{mode}" / ".loop" / "runtime" / phase / "INSTRUCTIONS.md"
    assert out.exists()
    return out.read_text()


def invariant_core(text):
    body = text.split("---", 2)[-1]
    regimes = json.loads((REPO / "regimes" / "regimes.json").read_text())
    values = set()
    for mode in regimes["defaults"]:
        values.update(regimes["defaults"][mode].values())
        for ph in regimes["phases"].values():
            values.update(ph.get("overrides", {}).get(mode, {}).values())
    lines = []
    for line in body.splitlines():
        if not any(v in line for v in values if len(v) > 3):
            lines.append(line)
    return "\n".join(lines)


def test_all_cells_compile(tmp_path):
    for phase, mode in CELLS:
        text = compile_cell(tmp_path, phase, mode)
        assert "GENERATED by enter_phase.py" in text
        assert not re.findall(r"\{\{[A-Z_]+\}\}", text), f"unbound in {phase}x{mode}"


def test_modes_differ_and_core_invariant(tmp_path):
    for phase in ("research", "design"):
        paired = compile_cell(tmp_path, phase, "paired")
        auto = compile_cell(tmp_path, phase, "auto")
        assert paired != auto, f"{phase}: modes produced identical bundles"
        assert invariant_core(paired) == invariant_core(auto), \
            f"{phase}: invariant core drifted between modes"


def test_design_auto_uses_frontier_clone(tmp_path):
    auto = compile_cell(tmp_path, "design", "auto")
    assert "FRONTIER clone" in auto
    paired = compile_cell(tmp_path, "design", "paired")
    assert "FRONTIER clone" not in paired


def test_mandates_generated(tmp_path):
    compile_cell(tmp_path, "research", "auto")
    m = tmp_path / "research-auto" / ".loop" / "runtime" / "research" / "mandate-researcher.md"
    assert m.exists()
    t = m.read_text()
    assert "CITABLE" in t and "{{SCHEMA_DIR}}" not in t
