#!/usr/bin/env python3
"""
enter_phase.py — Compile the current regime's instruction bundle.

Reads STATE.json (phase) and MISSION.md (mode policy vector), resolves the
regime from regimes/regimes.json, substitutes bindings into the phase's
discipline, prepares the environment, and prints the exact reading list.
Scripts prepare; models decide: this program only assembles.

Usage: python enter_phase.py [--project-dir DIR] [--check-only]
       [--phase P --mode M]   (compile an arbitrary cell; used by tests)
Exit: 0 ok, 1 refused (gate/state), 2 usage.
"""
import argparse
import datetime
import hashlib
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ORDER = ["research", "design", "implementation", "validation", "debug"]

MANDATES = {"research": ["mandate-researcher.md"],
            "design": ["mandate-critic.md", "mandate-implementability.md",
                        "mandate-griller.md"],
            "implementation": ["mandate-implementer.md"],
            "validation": ["mandate-validator.md"],
            "debug": ["mandate-experimenter.md"]}


def read_mode_vector(mission_path):
    text = mission_path.read_text()
    m = re.search(r"^Modes:\s*(\{.*\})\s*$", text, re.M)
    if not m:
        return None, "MISSION.md has no Modes: line"
    try:
        vec = json.loads(m.group(1).replace("'", '"'))
    except json.JSONDecodeError as e:
        return None, f"Modes vector is not valid JSON: {e}"
    bad = [p for p, v in vec.items() if v not in ("paired", "auto")]
    if bad:
        return None, f"Modes must be paired|auto; offending: {bad}"
    return vec, None


def resolve_regime(regimes, phase, mode):
    bindings = dict(regimes["defaults"][mode])
    bindings.update(regimes["phases"][phase].get("overrides", {}).get(mode, {}))
    return bindings


def compile_instructions(phase, mode, bindings, regimes):
    disc_path = REPO / "disciplines" / regimes["phases"][phase]["discipline"]
    body = disc_path.read_text()
    for slot, value in bindings.items():
        body = body.replace("{{" + slot + "}}", value)
    leftovers = sorted(set(re.findall(r"\{\{[A-Z_]+\}\}", body)))
    src_hash = hashlib.sha256(
        (disc_path.read_text() + json.dumps(regimes, sort_keys=True)).encode()
    ).hexdigest()[:12]
    stamp = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    header = (f"<!-- GENERATED by enter_phase.py — edit disciplines/ and "
              f"regimes/, never this file -->\n"
              f"<!-- regime: {phase} x {mode} | compiled: {stamp} | "
              f"sources sha: {src_hash} -->\n\n"
              f"# REGIME: {phase.upper()} in {mode.upper()} mode\n\n"
              f"Grilling in this phase: {regimes['phases'][phase]['grilling']}\n\n"
              f"---\n\n")
    footer = (f"\n---\n\n## Exit\n\nWrite the handoff (disciplines/handoff.md), "
              f"then run:\n`python {REPO}/compose/gate_check.py --phase {phase} "
              f"--advance`\n")
    return header + body + footer, leftovers, src_hash


def freshness_check(loop):
    """Implementation entry: banked sources must still match recorded hashes."""
    annex = loop / "design" / "sources-of-record.md"
    notes = []
    if not annex.exists():
        return ["WARN: no sources-of-record annex found"]
    for line in annex.read_text().splitlines():
        cells = [c.strip() for c in line.split("|")]
        if len(cells) >= 8 and re.fullmatch(r"[0-9a-f]{16,64}", cells[5] or ""):
            p = Path(cells[6])
            if not p.is_absolute():
                p = loop.parent / cells[6]
            if not p.exists():
                notes.append(f"DRIFT: banked bytes missing for {cells[1]} ({cells[6]})")
                continue
            actual = hashlib.sha256(p.read_bytes()).hexdigest()
            if not actual.startswith(cells[5]):
                notes.append(f"DRIFT: {cells[1]} bytes differ from recorded sha — "
                             f"file an UPSTREAM_DRIFT deviation before building")
    return notes or ["freshness: all banked sources match recorded hashes"]


def write_bundle(project, loop, phase, mode, bindings, regimes, text):
    runtime = loop / "runtime" / phase
    runtime.mkdir(parents=True, exist_ok=True)
    (runtime / "INSTRUCTIONS.md").write_text(text)
    for out in regimes["phases"][phase]["outputs"]:
        target = loop / out
        (target if out.endswith("/") else target.parent).mkdir(parents=True, exist_ok=True)
    for m in MANDATES[phase]:
        t = (REPO / "templates" / m).read_text()
        for slot, value in bindings.items():
            t = t.replace("{{" + slot + "}}", value)
        t = (t.replace("{{PROJECT}}", str(project))
              .replace("{{SCHEMA_DIR}}", str(REPO / "schemas"))
              .replace("{{MISSION_PATH}}", str(loop / "MISSION.md"))
              .replace("{{LEDGER_PATH}}", str(REPO / "preferences" / "PREFERENCES.md")))
        (runtime / m).write_text(t)
    return runtime


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project-dir", default=".")
    ap.add_argument("--check-only", action="store_true")
    ap.add_argument("--phase", choices=ORDER, help="with --mode: compile a cell directly")
    ap.add_argument("--mode", choices=["paired", "auto"])
    args = ap.parse_args()

    project = Path(args.project_dir).resolve()
    loop = project / ".loop"
    regimes = json.loads((REPO / "regimes" / "regimes.json").read_text())

    # Direct-cell path (tests and inspection): no state required.
    if args.phase and args.mode:
        bindings = resolve_regime(regimes, args.phase, args.mode)
        text, leftovers, src_hash = compile_instructions(args.phase, args.mode,
                                                         bindings, regimes)
        if leftovers:
            print(f"REFUSED: unbound slots {leftovers}")
            return 1
        if args.check_only:
            print(f"OK: {args.phase} x {args.mode} (sha {src_hash})")
            return 0
        loop.mkdir(parents=True, exist_ok=True)
        runtime = write_bundle(project, loop, args.phase, args.mode, bindings,
                               regimes, text)
        print(f"COMPILED: {runtime / 'INSTRUCTIONS.md'}")
        return 0

    state_p = loop / "STATE.json"
    if not state_p.exists():
        print("No .loop/STATE.json — run compose/bootstrap.py first.")
        return 2
    state = json.loads(state_p.read_text())
    phase = state["phase"]
    if phase == "complete":
        print("Mission COMPLETE. bootstrap.py --new-mission starts the next one.")
        return 0

    idx = ORDER.index(phase)
    if idx > 0 and phase != "debug":
        passed = [g["phase"] for g in state.get("gate_history", [])]
        if ORDER[idx - 1] not in passed:
            print(f"REFUSED: no passed gate on record for '{ORDER[idx-1]}'. "
                  f"Run gate_check.py --phase {ORDER[idx-1]} --advance first.")
            return 1
    if not state.get("mission_confirmed"):
        print("REFUSED: MISSION.md unconfirmed. Grill it, get the confirmation "
              "the regime requires, set mission_confirmed=true in STATE.json.")
        return 1

    vec, err = read_mode_vector(loop / "MISSION.md")
    if err:
        print(f"REFUSED: {err}")
        return 1
    mode = vec.get(phase, "paired")
    bindings = resolve_regime(regimes, phase, mode)
    text, leftovers, src_hash = compile_instructions(phase, mode, bindings, regimes)
    if leftovers:
        print(f"REFUSED: unbound slots {leftovers} — add them to regimes.json")
        return 1
    if args.check_only:
        print(f"OK: {phase} x {mode} compiles clean (sha {src_hash})")
        return 0

    runtime = write_bundle(project, loop, phase, mode, bindings, regimes, text)
    if phase == "implementation":
        print("\n".join(freshness_check(loop)))

    reading = [str(runtime / "INSTRUCTIONS.md"), str(loop / "MISSION.md")]
    prev_art = {"design": "research/synthesis.md",
                "implementation": "design/sources-of-record.md",
                "validation": "validation/checklist.md",
                "debug": "validation/verdicts/"}.get(phase)
    if prev_art:
        reading.append(str(loop / prev_art))
    print(f"COMPILED: {phase} x {mode} (sources sha {src_hash})")
    print("READ EXACTLY THESE, NOTHING MORE:")
    for r in reading:
        print(f"  - {r}")
    print(f"Worker mandates ready in {runtime}/ — fill task slots, point "
          f"workers at the files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
